#!/bin/bash
#SBATCH --account=def-patricia
#SBATCH --gres=gpu:v100l:1       # Request GPU "generic resources"
#SBATCH --cpus-per-task=6  # Cores proportional to GPUs: 6 on Cedar, 16 on Graham.
#SBATCH --mem=187G       # Memory proportional to GPUs: 32000 Cedar, 64000 Graham.
#SBATCH --time=0-16:00
#SBATCH --output=../../reports/vggnet-%N-%j.out

module purge

module load python/3.7.9

module load cuda/11.2.2 cudnn/8.2.0

export XLA_FLAGS=--xla_gpu_cuda_data_dir=$EBROOTCUDA
export XLA_PYTHON_CLIENT_PREALLOCATE=false


virtualenv --no-download $SLURM_TMPDIR/env
source $SLURM_TMPDIR/env/bin/activate
pip install --no-index --upgrade pip

pip install --no-index torch
pip install --no-index pytorch_lightning
pip install --no-index tensorflow
pip install --no-index matplotlib
pip install --no-index wandb
pip install --no-index nilearn
pip install --no-index nibabel
pip install --no-index pandas
pip install --no-index torchvision
#pip install --no-index glob2
pip install --no-index torchio

python /home/spinney/project/spinney/deep/src/models/vggnet.py --name vggnet-large --data_dir $SCRATCH/enigma_drug/data --batch_size 16  --max_epochs 8 --num_workers 4 --num_samples -1 --learning_rate 0.0001 --cropped True --seed 42 --optim adam --num_classes 5
